# minikube ssh
# minikube mkdir /tmp/jaeger
# kubectl get pv
# kubectl describe pv/task-pv-volume
kind: PersistentVolume
apiVersion: v1
metadata:
  name: task-pv-volume
  labels:
    type: local
spec:
  storageClassName: manual
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/tmp/jaeger"
